### ISSUE TITLE
Installer doesn't contain SQL Scripts

### ISSUE THREAD

**Issue by chmichael** [Dravion/hmailserver#1]
Hello,
  Installer doesn't include the SQL scripts to update the database.

  I also needed to run this script additionally! (i don't know if they have included it in the main repository)
  https://www.hmailserver.com/forum/viewtopic.php?f=10&t=38294&p=236639&hilit=dbversion+5702#p236639

Thank you for this build! :)

**Comment by Dravion** [comment]
Tbh i never checked the an upgrade installation. Can you describe in what Problems did you run into?

**Comment by chmichael** [comment]
The v5.6.8 release you have requires a database with version 5702 but when you upgrade to your build it doesn't upgrade the database! The current stable official hMailServer database version is 5608 i think!

**Comment by Dravion** [comment]
Ok, i will take a look into this. It's nothing dramatic bc the database structure hasn't been touch at the official release level for years. As a quick work around you can download this little utility and update the table Eversion yourself in no time
https://github.com/Dravion/hMSSqlPad/releases/tag/1.0.0.1

Use username Administrator and your hMailServer password
At the input field delete the existing SQL-Query and execute
**UPDATE hm_dbversion SET value = 5702** (or what ever db version nr you need^^)

**Comment by chmichael** [comment]
If you change the value of hm_dbversion to 5702 it works but the official 5.6.8 32-bit version is "56xx",
It seems that Martin merged the 5.7 code into the main branch and you forked that!

Just to let you know! :)

**Comment by chmichael** [comment]
It seems you re-fork so i close this issue! :)

**Comment by Dravion** [comment]
That's correct, The Fork is from hmailserver/hmailserver and my Private Development for. My LTS marked builds are also from  a different form then this, it's from https://github.com/hMailServer-Long-Term-Support-LTS code but still 5.7 of hmailserver/hmailserver main upstream Branch. I will transfer the LTS builds to the LTS repo. This repo will be used for new Feature development only (which might be incompatible with official hMailServer and LTS hMailServer).

**Comment by chmichael** [comment]
Ok!
