### ISSUE TITLE
hmailserver with .net Core ?

### ISSUE THREAD

**Issue by chmichael** [Dravion/hmailserver#2]
Hello,
  Is it possible to compile with .net Core 6/ .NET 6.0 ?
  
  Thank you

**Comment by Dravion** [comment]
> Hello, Is it possible to compile with .net Core 6/ .NET 6.0 ?
> 
> Thank you

Hi, i totally missed your post :d

No. The Server is made in C/C++ and the Client Tools in .NET 4.5 Standard (the Project is something 20 yrs old).

**Comment by chmichael** [comment]
Ok Thank you!
